version: "3.8"
services:

  # Portainer - Docker 管理工具
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  # Minecraft 服务器
  mcserver:
    image: marctv/minecraft-papermc-server:latest
    container_name: mcserver
    restart: unless-stopped
    environment:
      - MEMORYSIZE=1G
      - PAPERMC_FLAGS=
    volumes:
      - mcserver_data:/data:rw
    ports:
      - 25565:25565
    tty: true

  # 文件浏览器
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: always
    ports:
      - "8090:80"
    volumes:
      - /:/data  # 将主机的根目录挂载到容器的 /data 目录
    environment:
      - DATA_DIR=/  # 设置容器访问主机根目录的路径
      - TZ=Asia/Shanghai  # 设置时区
      - USERNAME=admin    # 设置登录用户名
      - PASSWORD=admin123 # 设置登录密码

  # ChatGPT Web
  chatgpt-web:
    image: chatgptweb/chatgpt-web:latest
    container_name: chatgpt_web
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ACCESS_TOKEN=your_access_token  # 替换为您的 Access Token

  # AdGuardHome 广告过滤器
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - adguardhome_work:/opt/adguardhome/work
      - adguardhome_conf:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:3000/tcp"

  # Alist 文件管理工具
  alist:
    image: xhofe/alist-aria2
    container_name: alist
    restart: unless-stopped
    ports:
      - "5244:5244"
      - "6800:6800"
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - alist_data:/opt/alist/data
      - alist_config:/etc/alist

  # aaPanel - 面板管理工具
  aapanel:
    image: aapanel/aapanel:lnmp
    container_name: aapanel
    network_mode: host
    restart: unless-stopped
    volumes:
      - website_data:/www/wwwroot
      - mysql_data:/www/server/data
      - vhost:/www/server/panel/vhost

  # Calibre Web - 电子书管理工具
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - calibre_web_data:/config
      - calibre_library:/books
    ports:
      - 8083:8083
    restart: unless-stopped

  # KodBox - 文件管理工具
  kodbox:
    image: kodcloud/kodbox
    container_name: kodbox
    ports:
      - 89:80
    volumes:
      - kodbox_data:/var/www/html
    restart: unless-stopped

  # Nginx Proxy Manager
  nginx:
    image: jc21/nginx-proxy-manager
    container_name: nginx
    restart: unless-stopped
    network_mode: host
    volumes:
      - nginx_data:/data
      - letsencrypt:/etc/letsencrypt

  # qBittorrent 下载工具
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent_config:/config
      - qbittorrent_downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  # Qinglong - 自动化脚本
  qinglong:
    image: whyour/qinglong
    container_name: qinglong
    hostname: qinglong
    restart: unless-stopped
    ports:
      - 5700:5700
    volumes:
      - qinglong_data:/ql/data

  # Vaultwarden - 密码管理
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - vaultwarden_data:/data
    ports:
      - 86:80
    environment:
      - PUID=0
      - PGID=0

  # Watchtower - 自动更新容器
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --cleanup

  # WireGuard Easy - VPN
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=raspberrypi.local
      - PASSWORD=foobar123
      - WG_PORT=51820
    volumes:
      - wireguard:/etc/wireguard
    ports:
      - 51822:51820/udp
      - 51821:51821/tcp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

  # Photoprism - 照片管理工具
  photoprism:
    image: photoprism/photoprism
    container_name: photoprism
    ports:
      - "2342:2342"
    environment:
      - PHOTOPRISM_ADMIN_PASSWORD=photoprism
    volumes:
      - photoprism_data:/photoprism
    restart: unless-stopped

  # Vocechat - 聊天工具
  vocechat:
    image: privoce/vocechat-server:latest
    container_name: vocechat-server
    restart: unless-stopped
    ports:
      - '3019:3000'
    volumes:
      - '/root/vocechat:/home/vocechat-server/data'

  # XUI - 管理面板
  xui:
    image: enwaiax/x-ui:alpha-zh
    container_name: xui
    volumes:
      - xui_db:/etc/x-ui/
      - xui_cert:/root/cert/
    restart: unless-stopped
    network_mode: host

  # MySQL 数据库
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "3306:3306"

  # WordPress 网站
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    ports:
      - "8089:80"

  # Nextcloud - 云存储
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - "8095:80"
    volumes:
      - nextcloud:/home/wwwroot/nextcloud

  # Redis 数据库
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --save 60 1 --loglevel warning --requirepass yourpassword
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

# 持久化存储卷
volumes:
  portainer_data:
  mcserver_data:
  adguardhome_work:
  adguardhome_conf:
  alist_data:
  alist_config:
  website_data:
  mysql_data:
  vhost:
  calibre_web_data:
  calibre_library:
  kodbox_data:
  nginx_data:
  letsencrypt:
  qbittorrent_config:
  qbittorrent_downloads:
  qinglong_data:
  vaultwarden_data:
  wireguard:
  photoprism_data:
  xui_db:
  xui_cert:
  nextcloud:
  redis_data:

